# Generated by Django 5.2.8 on 2025-11-21 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('cash', 'Efectivo'), ('yape', 'Yape'), ('plin', 'Plin'), ('transfer', 'Transferencia')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='payments/')),
                ('validation_status', models.CharField(choices=[('pending', 'Pendiente de Validación'), ('validated', 'Validado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('motivo_anulacion', models.TextField(blank=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('comprobante_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('internet', 'Internet'), ('cable', 'Cable')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('install_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigPreciosZona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicio', models.CharField(choices=[('internet', 'Internet'), ('cable', 'Cable')], max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vigencia_desde', models.DateField()),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='core.caserio')),
            ],
            options={
                'verbose_name': 'Configuración de Precio por Zona',
                'verbose_name_plural': 'Configuraciones de Precios por Zona',
                'ordering': ['-vigencia_desde'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('expired', 'Vencido')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='core.client')),
            ],
        ),
    ]
